### ISSUE TITLE
What does label.vocab contains

### ISSUE THREAD

**Issue by FallakAsad** [stevezheng23/xlnet_extension_tf#58]
Just to test the implementation, I took the conll2003 data from this link https://github.com/synalp/NER/tree/master/corpus/CoNLL-2003 and then added a resource/label.vocab file in ${DATADIR}. My label.vocab file contains following entities:
I-PER
B-PER 
I-LOC
B-LOC
I-MISC
B-MISC
I-ORG
B-ORG

But when I run the training script, it gives me following error:
Traceback (most recent call last):
  File "run_ner.py", line 855, in <module>
    tf.app.run()
  File "/home/falak/.local/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/falak/.local/lib/python3.5/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/falak/.local/lib/python3.5/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "run_ner.py", line 786, in main
    train_features = example_converter.convert_examples_to_features(train_examples)
  File "run_ner.py", line 381, in convert_examples_to_features
    feature = self.convert_single_example(example, logging=(idx < 5))
  File "run_ner.py", line 327, in convert_single_example
    label_ids.append(self.label_map[labels[i]])
KeyError: 'O'

This error disappears if I add following additional entities in label.vocab:

O
X
\<sep\>
\<unk\>
\<s\>
\</s>
\<cls\>
\<sep\>
\<pad\>
\<mask\>
\<eod\>
\<eop\>

So, is it expected to add these entities in label.vocab file?

**Comment by stevezheng23** [comment]
@FallakAsad , you can try out the following label voacb
```
<pad>
O
X
<cls>
<sep>
B-LOC
B-MISC
B-ORG
B-PER
I-LOC
I-MISC
I-ORG
I-PER
```

**Comment by FallakAsad** [comment]
Thanks it worked.
